### ISSUE TITLE
Implement WebAPI endpoints

### ISSUE THREAD

**Issue by MarcellHarmaci** [SandorBalazsHU/elte-ik-msc-weather-cam#21]
## measurements
- [x] `GET /stations/{station_id}/measurements/{measurement_id}`
Find a single measurement of a station.
- [x] `GET /stations/{station_id}/measurements/latest`
Find the latest measurement of a station.
- [x] `GET /stations/{station_id}/measurements/first`
Find the first measurement of a station.
- [x] `GET /stations/{station_id}/measurements`
Find multiple measurements of a station in a given time range or relative to a measurement.
- [x] `POST /stations/measurements`
Add new measurements to server
*Note: I didn't find in the API documentation how the api key will be sent to the server. noratanX let me know, that it will be in the `api_key` HTTP header.*

## pictures
- [x] `GET /stations/{station_id}/pictures/{picture_id}`
Find picture by id.
- [x] `GET /stations/{station_id}/pictures/latest`
Find last picture.
- [x] `GET /stations/{station_id}/pictures`
Find picture relative to other picture.
- [x] `POST /stations/pictures`
Add picture to server.

*Note: In order to implement these endpoints I need to know what kind of image format can the Android front-end use. I suggest to transmit the images as base64 encoded strings in the requests' body.* @szokolimatyas 

## stations
- [x] `GET /stations/{station_id}/api`
Returns part of the API key for a station.
- [x] `GET /stations/{station_id}/ping`
Pings the weather station.
- [x] `GET /stations/pictures/storage`
Returns information about the storage server for the pictures.
- [x] `GET /stations/measurements/storage`
Returns information about the storage server for the measurements.
- [x] `PUT /stations/status/{status_code}`
Update the status of the weather station.

*Notes to storage endpoints:*
- *The image and DB storage are on the same disk, so they will return the same results.*
- *They should be tested on the production server, because it uses OS level linux commands*

## user
- [x] `GET /user`
Gets data about the logged in user.
- [x] `GET /user/login`
Logs user into the system
- [x] `GET /user/logout`
Logs out current logged in user.
- [x] `GET /user/stations`
Returns an array of stations registered with the user.
- [x] `POST /user/stations/{station_name}`
Add new stations to the user.
- [x] `PUT /user/stations/{station_id}`
Generate new API key for a station.
- [x] `POST /user/register`
Add new user.
- [x] `PUT /user/{username}`
Update user data.
- [x] `DELETE /user/{username}`
Delete user.
*Note: this will be one of the last endpoint I implement. I need to know what to delete to remove all the data created by a user.*

**Comment by szokolimatyas** [comment]
Also I have been having problems with using prism on my local machine and reaching it from the android env. The mock server seems to be reachable though.

**Comment by szokolimatyas** [comment]
The content-type is an octet stream, and the content itself is bytes read straight from a jpeg image.
Some code:
```kotlin
            val bytes = file.readBytes()
            val body =
                bytes.toRequestBody("application/octet-stream".toMediaTypeOrNull(), 0, bytes.size)
            val res = picturesService.addPicture("application/octet-stream", body)
```
The Retrofit API:
```kotlin
    @POST("stations/pictures/")
    suspend fun addPicture(@Header("Content-Type") mime: String,
                           @Body body: RequestBody):
            Response<ApiResponseEntity>
```
Example request inspected:
![image](https://user-images.githubusercontent.com/56924108/205496129-b5b842b2-5973-4b87-851b-d55c880373f6.png)
