### ISSUE TITLE
Station statuses

### ISSUE THREAD

**Issue by MarcellHarmaci** [SandorBalazsHU/elte-ik-msc-weather-cam#27]
### We need to discuss what kind of statuses will the weather stations have.
According to the API documentation it will be represented as an integer.

This issue is blocking:
- the implementation of endpoint: `GET /stations/{station_id}/ping`
- the weather stations' status reporting through `PUT /stations/status/{status_code}`
- the web interface displaying this data

**Comment by szokolimatyas** [comment]
A few preliminary ones:
- 500 Internal Station Error (misc. errors)
- 501 Camera Error 
- 400 Hardware Unavailable
- XXX Low Battery Warning
- XXX Malformed Hardware Measurement Data

**Comment by MarcellHarmaci** [comment]
Then let me add:
- 200 OK (station online and working correctly)

**Comment by szokolimatyas** [comment]
For now, we could limit ourselves to a simple:
- 200 OK
- 500 Internal Error
After the integration works, we could add a flag system that I talked about.

**Comment by MarcellHarmaci** [comment]
Okay, for now I will mark this issue resolved, but we could reopen/reference it once we want to add more statuses.
